Refactor admin tables
Ikkjo/team10-isa-mrs pull request #69
Opened 2022-06-18 17:42 UTC by iAmNikola

2022-06-18 18:54 UTC, therealtgd requested changes

2022-06-18 18:54 UTC, therealtgd commented on backend/src/main/java/team10/app/service/AdminService.java
> +        switch (sortTokens[0]) {
Ovo mozes napraviti preko if else na sledeci nacin:
`sortTokens[0].equals("registrationReason") ? sortTokens[0] = "description" : sortTokens[0] = "businessClient."+sortTokens[0] `

2022-06-18 18:54 UTC, therealtgd commented on backend/src/main/java/team10/app/service/AdminService.java
> +        switch (sortTokens[0]) {
zamijeni sve ovo sa `sortTokens[0] = "user."+sortTokens[0]`

2022-06-19 00:27 UTC, iAmNikola commented on backend/src/main/java/team10/app/service/AdminService.java
> +        switch (sortTokens[0]) {
Genijalno

2022-06-19 00:30 UTC, iAmNikola commented on backend/src/main/java/team10/app/service/AdminService.java
> +        switch (sortTokens[0]) {
Ne moze zbog deletion reason sortToken koji je moguć i ne treba mu 'user' prefiks ali moze se refaktorisati da bude mnogo čitljivije. Pushovaću promene u sledecem commitu

2022-06-19 00:38 UTC, merged